/* ================================================================
   SECTION 2 — WAREHOUSES & RESOURCE MONITOR
   ================================================================ */
CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'File validation and COPY INTO loads';
 
CREATE WAREHOUSE IF NOT EXISTS DBT_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'dbt builds';
 
CREATE WAREHOUSE IF NOT EXISTS BI_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'BI consumption';
 
CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'Cortex Analyst / Search';
 
CREATE WAREHOUSE IF NOT EXISTS ML_WH
    WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'Feature engineering / scoring';
 
CREATE RESOURCE MONITOR IF NOT EXISTS FINTECH_PROJECT_MONITOR
    WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 50 PERCENT DO NOTIFY ON 75 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
 
ALTER WAREHOUSE INGEST_WH SET RESOURCE_MONITOR = FINTECH_PROJECT_MONITOR;
ALTER WAREHOUSE DBT_WH SET RESOURCE_MONITOR = FINTECH_PROJECT_MONITOR;
ALTER WAREHOUSE BI_WH SET RESOURCE_MONITOR = FINTECH_PROJECT_MONITOR;
ALTER WAREHOUSE CORTEX_WH SET RESOURCE_MONITOR = FINTECH_PROJECT_MONITOR;
ALTER WAREHOUSE ML_WH SET RESOURCE_MONITOR = FINTECH_PROJECT_MONITOR;