/* ================================================================
   SECTION 7 — PARTNER TRANSACTIONS (event-driven, Snowpipe helps in loading semi-structured data to Snowflake)

AUTO_INGEST = TRUE (The Event Trigger)
This is the heart of Snowpipe automation.

What it does: It tells Snowflake to listen for a notification event (usually an SQS message sent via S3 Event Notifications) whenever a new file is uploaded to the stage.

What you must remember: Simply setting this to TRUE does not automatically make it work. You must configure S3 to send events to the specific SQS queue ARN generated by Snowflake for this pipe.

How to get the ARN: 
Run SHOW PIPES; 

DESCRIBE PIPE FINTECH_PROD.RAW.PARTNER_TXN_PIPE; 

copy the notification_channel value to paste into your S3 Event Notification bucket configuration.
   ================================================================ */
CREATE STAGE IF NOT EXISTS FINTECH_PROD.RAW.PARTNER_TXN_STAGE
    URL = 's3://fintech-project-sriram2026/partner_transactions/'
    STORAGE_INTEGRATION = FINTECH_S3_INT
    FILE_FORMAT = FINTECH_PROD.RAW.NDJSON_FORMAT;

-- VARIANT is a specialized, proprietary data type designed specifically to store semi-structured data.
CREATE TABLE IF NOT EXISTS FINTECH_PROD.RAW.PARTNER_TRANSACTIONS (
    raw_payload     VARIANT,
    _loaded_at      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _source_file    STRING
);

-- Creating a Pipe Object and Loading data 
-- $1 means "the first column/element of the file."
-- For your newline-delimited JSON (NDJSON_FORMAT), each line is a single JSON object. Therefore, the entire JSON object on each line is treated as the "first column" ($1).
-- METADATA$FILENAME: This is a built-in Snowflake pseudo-column. It grabs the exact filename and path of the file currently being processed in S3 (for example:

CREATE PIPE IF NOT EXISTS FINTECH_PROD.RAW.PARTNER_TXN_PIPE
    AUTO_INGEST = TRUE
AS
COPY INTO FINTECH_PROD.RAW.PARTNER_TRANSACTIONS (raw_payload, _source_file)
FROM (SELECT $1, METADATA$FILENAME FROM @FINTECH_PROD.RAW.PARTNER_TXN_STAGE)
FILE_FORMAT = (FORMAT_NAME = FINTECH_PROD.RAW.NDJSON_FORMAT)
ON_ERROR = 'CONTINUE';

-- After pipe creation we need to get the Notication channel from Pipe which we paste inside S3 Event Notifications 
-- S3 Publishes: S3 fires an s3:ObjectCreated:* event notification containing the file metadata upon successful object upload.
--SQS Buffers: This event payload is pushed asynchronously to the Snowflake-managed SQS queue (the ARN target).--
-- Snowpipe Consumes: Snowpipe polls the queue, extracts the file path, and triggers serverless compute to execute the ingestion pipeline.

SHOW PIPES LIKE 'PARTNER_TXN_PIPE' IN SCHEMA FINTECH_PROD.RAW;

SELECT COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS

SELECT * FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS;

SELECT 
    raw_payload:transaction_id::STRING       AS transaction_id,
    raw_payload:account_id::STRING           AS account_id,
    raw_payload:merchant_id::STRING         AS merchant_id,
    raw_payload:amount::FLOAT                AS amount,
    raw_payload:currency::STRING             AS currency,
    raw_payload:authorization_status::STRING AS authorization_status,
    raw_payload:channel::STRING              AS channel,
    raw_payload:device_id::STRING            AS device_id,
    raw_payload:event_id::STRING             AS event_id,
    raw_payload:event_timestamp::TIMESTAMP_TZ AS transaction_timestamp,
    _source_file,
    _loaded_at
FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS;
