SELECT 'settlements' AS source, COUNT(*) AS row_count, MAX(_loaded_at) AS last_loaded FROM FINTECH_PROD.RAW.SETTLEMENTS
UNION ALL
SELECT 'partner_transactions', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS
UNION ALL
SELECT 'customers_files', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.CUSTOMERS_API_RAW
UNION ALL
SELECT 'accounts_files', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.ACCOUNTS_API_RAW
UNION ALL
SELECT 'merchants_files', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.MERCHANTS_API_RAW
UNION ALL
SELECT 'support_cases', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.SUPPORT_CASES
UNION ALL
SELECT 'policy_documents', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.POLICY_DOCUMENTS
UNION ALL
SELECT 'exchange_rates', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.EXTERNAL_EXCHANGE_RATES
UNION ALL
SELECT 'account_activity_raw', COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.ACCOUNT_ACTIVITY
UNION ALL
SELECT 'accounts_current_core', COUNT(*), MAX(_merged_at) FROM FINTECH_PROD.CORE.ACCOUNTS_CURRENT
ORDER BY source;


select * FROM FINTECH_PROD.RAW.SETTLEMENTS