SELECT * FROM FINTECH_PROD.RAW.accounts_api_raw

SELECT * FROM FINTECH_PROD.STAGING.STG_ACCOUNTS LIMIT 10;

SELECT COUNT(*) FROM FINTECH_PROD.STAGING.STG_ACCOUNTS;

SELECT * FROM FINTECH_PROD.CORE.ACCOUNTS_CURRENT;

USE ROLE ACCOUNTADMIN;

GRANT SELECT ON TABLE FINTECH_PROD.CORE.ACCOUNTS_CURRENT TO ROLE FINTECH_TRANSFORMER;

-- also cover any future tables ACCOUNTADMIN/FINTECH_ADMIN creates in
-- CORE outside of dbt, so this doesn't happen again for a different table
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.CORE TO ROLE FINTECH_TRANSFORMER;

SELECT * FROM FINTECH_PROD.STAGING.STG_ACCOUNTS_CURRENT LIMIT 5;

USE ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE FINTECH_PROD.CORE.ACCOUNTS_CURRENT TO ROLE FINTECH_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.CORE TO ROLE FINTECH_TRANSFORMER;


CREATE OR REPLACE TABLE FINTECH_PROD.CORE.ACCOUNTS_CURRENT AS
SELECT * FROM FINTECH_PROD.CORE.ACCOUNTS_CURRENT
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY account_id
    ORDER BY _merged_at DESC
) = 1;

USE ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;

USE ROLE FINTECH_TRANSFORMER;
SELECT COUNT(*), COUNT(DISTINCT account_id) FROM FINTECH_PROD.INTERMEDIATE.INT_ACCOUNTS_ENRICHED;

SELECT has_activity_history, COUNT(*)
FROM FINTECH_PROD.INTERMEDIATE.INT_ACCOUNTS_ENRICHED
GROUP BY 1;

DROP TABLE IF EXISTS FINTECH_PROD.STAGING.MY_FIRST_DBT_MODEL;
DROP VIEW IF EXISTS FINTECH_PROD.STAGING.MY_SECOND_DBT_MODEL;

DROP VIEW IF EXISTS FINTECH_PROD.STAGING.INT_ACCOUNTS_ENRICHED;


USE ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL VIEWS IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL VIEWS IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;

TRUNCATE TABLE FINTECH_PROD.RAW.SETTLEMENTS;
TRUNCATE TABLE FINTECH_PROD.RAW.PARTNER_TRANSACTIONS;
TRUNCATE TABLE FINTECH_PROD.RAW.SUPPORT_CASES;

SELECT COUNT(*) as total, COUNT(DISTINCT f.value:customer_id::string) as unique_ids
FROM FINTECH_PROD.RAW.CUSTOMERS_API_RAW, LATERAL FLATTEN(input => raw_payload:records) f;

COPY INTO FINTECH_PROD.RAW.SETTLEMENTS
    (settlement_id, transaction_id, account_id, merchant_id,
     transaction_timestamp, settlement_date, amount, currency,
     settlement_status, fee_amount)
FROM @FINTECH_PROD.RAW.SETTLEMENTS_STAGE
FILE_FORMAT = (FORMAT_NAME = FINTECH_PROD.RAW.CSV_FORMAT)
PATTERN = '.*\\.csv'
ON_ERROR = 'CONTINUE';

-- support_cases
COPY INTO FINTECH_PROD.RAW.SUPPORT_CASES (raw_payload, _source_file)
FROM (SELECT $1, METADATA$FILENAME FROM @FINTECH_PROD.RAW.SUPPORT_CASES_STAGE)
FILE_FORMAT = (FORMAT_NAME = FINTECH_PROD.RAW.NDJSON_FORMAT)
ON_ERROR = 'CONTINUE';

-- partner_transactions loads automatically via Snowpipe — no COPY INTO needed,
-- just confirm it landed:
SELECT COUNT(*), MAX(_loaded_at) FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS;

GRANT USAGE ON INTEGRATION DBT_EXT_ACCESS TO ROLE FINTECH_TRANSFORMER;

DROP VIEW IF EXISTS FINTECH_PROD.STAGING.MART_CUSTOMER_360;
DROP VIEW IF EXISTS FINTECH_PROD.STAGING.MART_DAILY_TRANSACTION_KPI;
DROP VIEW IF EXISTS FINTECH_PROD.STAGING.MART_MERCHANT_PERFORMANCE;