SELECT * FROM FINTECH_PROD.RAW.accounts_api_raw

SELECT * FROM FINTECH_PROD.STAGING.STG_ACCOUNTS LIMIT 10;

SELECT COUNT(*) FROM FINTECH_PROD.STAGING.STG_ACCOUNTS;

SELECT * FROM FINTECH_PROD.CORE.ACCOUNTS_CURRENT;


