SELECT * FROM FINTECH_PROD.RAW.accounts_api_raw

SELECT * FROM FINTECH_PROD.STAGING.STG_ACCOUNTS LIMIT 10;

SELECT COUNT(*) FROM FINTECH_PROD.STAGING.STG_ACCOUNTS;

SELECT * FROM FINTECH_PROD.CORE.ACCOUNTS_CURRENT;

USE ROLE ACCOUNTADMIN;

GRANT SELECT ON TABLE FINTECH_PROD.CORE.ACCOUNTS_CURRENT TO ROLE FINTECH_TRANSFORMER;

-- also cover any future tables ACCOUNTADMIN/FINTECH_ADMIN creates in
-- CORE outside of dbt, so this doesn't happen again for a different table
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.CORE TO ROLE FINTECH_TRANSFORMER;

SELECT * FROM FINTECH_PROD.STAGING.STG_ACCOUNTS_CURRENT LIMIT 5;

USE ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE FINTECH_PROD.CORE.ACCOUNTS_CURRENT TO ROLE FINTECH_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.CORE TO ROLE FINTECH_TRANSFORMER;


CREATE OR REPLACE TABLE FINTECH_PROD.CORE.ACCOUNTS_CURRENT AS
SELECT * FROM FINTECH_PROD.CORE.ACCOUNTS_CURRENT
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY account_id
    ORDER BY _merged_at DESC
) = 1;

USE ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;

USE ROLE FINTECH_TRANSFORMER;
SELECT COUNT(*), COUNT(DISTINCT account_id) FROM FINTECH_PROD.INTERMEDIATE.INT_ACCOUNTS_ENRICHED;

SELECT has_activity_history, COUNT(*)
FROM FINTECH_PROD.INTERMEDIATE.INT_ACCOUNTS_ENRICHED
GROUP BY 1;

DROP TABLE IF EXISTS FINTECH_PROD.STAGING.MY_FIRST_DBT_MODEL;
DROP VIEW IF EXISTS FINTECH_PROD.STAGING.MY_SECOND_DBT_MODEL;

DROP VIEW IF EXISTS FINTECH_PROD.STAGING.INT_ACCOUNTS_ENRICHED;


USE ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL VIEWS IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FINTECH_PROD.STAGING TO ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL VIEWS IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE ACCOUNTADMIN;

