/* ================================================================
   SECTION 3 — RBAC ROLES
   ================================================================ */
CREATE ROLE IF NOT EXISTS FINTECH_LOADER;
CREATE ROLE IF NOT EXISTS FINTECH_TRANSFORMER;
CREATE ROLE IF NOT EXISTS FINTECH_ANALYST;
CREATE ROLE IF NOT EXISTS FINTECH_ML_ENGINEER;
CREATE ROLE IF NOT EXISTS FINTECH_ADMIN;
 
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE FINTECH_LOADER;
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE FINTECH_ANALYST;
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE FINTECH_ANALYST;
GRANT USAGE ON WAREHOUSE ML_WH TO ROLE FINTECH_ML_ENGINEER;
 
GRANT USAGE ON DATABASE FINTECH_PROD TO ROLE FINTECH_LOADER;
GRANT USAGE ON DATABASE FINTECH_PROD TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE ON DATABASE FINTECH_PROD TO ROLE FINTECH_ANALYST;
GRANT USAGE ON DATABASE FINTECH_PROD TO ROLE FINTECH_ML_ENGINEER;
GRANT USAGE ON DATABASE FINTECH_PROD TO ROLE FINTECH_ADMIN;
 
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE PIPE
    ON SCHEMA FINTECH_PROD.RAW TO ROLE FINTECH_LOADER;
GRANT USAGE ON SCHEMA FINTECH_PROD.RAW TO ROLE FINTECH_TRANSFORMER;
 
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FINTECH_PROD.STAGING TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FINTECH_PROD.INTERMEDIATE TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FINTECH_PROD.CORE TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA FINTECH_PROD.MARTS TO ROLE FINTECH_TRANSFORMER;
 
GRANT USAGE ON SCHEMA FINTECH_PROD.MARTS TO ROLE FINTECH_ANALYST;
GRANT USAGE ON SCHEMA FINTECH_PROD.SEMANTIC TO ROLE FINTECH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FINTECH_PROD.MARTS TO ROLE FINTECH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTECH_PROD.MARTS TO ROLE FINTECH_ANALYST;
 
GRANT USAGE, CREATE TABLE ON SCHEMA FINTECH_PROD.ML TO ROLE FINTECH_ML_ENGINEER;
 
GRANT ALL ON DATABASE FINTECH_PROD TO ROLE FINTECH_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE FINTECH_PROD TO ROLE FINTECH_ADMIN;
 
-- >>> EDIT: replace <your_username> with your real Snowflake username <<<
GRANT ROLE FINTECH_ADMIN TO USER SRIRAMVZ;
GRANT ROLE FINTECH_LOADER TO ROLE FINTECH_ADMIN;
GRANT ROLE FINTECH_TRANSFORMER TO ROLE FINTECH_ADMIN;
GRANT ROLE FINTECH_ANALYST TO ROLE FINTECH_ADMIN;
GRANT ROLE FINTECH_ML_ENGINEER TO ROLE FINTECH_ADMIN;