CREATE STAGE IF NOT EXISTS FINTECH_PROD.RAW.CUSTOMERS_API_STAGE
    URL = 's3://fintech-project-sriram2026/source_api/customers/'
    STORAGE_INTEGRATION = FINTECH_S3_INT
    FILE_FORMAT = FINTECH_PROD.RAW.NDJSON_FORMAT;
 
CREATE STAGE IF NOT EXISTS FINTECH_PROD.RAW.ACCOUNTS_API_STAGE
    URL = 's3://fintech-project-sriram2026/source_api/accounts/'
    STORAGE_INTEGRATION = FINTECH_S3_INT
    FILE_FORMAT = FINTECH_PROD.RAW.NDJSON_FORMAT;
 
CREATE STAGE IF NOT EXISTS FINTECH_PROD.RAW.MERCHANTS_API_STAGE
    URL = 's3://fintech-project-sriram2026/source_api/merchants/'
    STORAGE_INTEGRATION = FINTECH_S3_INT
    FILE_FORMAT = FINTECH_PROD.RAW.NDJSON_FORMAT;
 
CREATE TABLE IF NOT EXISTS FINTECH_PROD.RAW.CUSTOMERS_API_RAW (
    raw_payload VARIANT, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _source_file STRING
);
CREATE TABLE IF NOT EXISTS FINTECH_PROD.RAW.ACCOUNTS_API_RAW (
    raw_payload VARIANT, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _source_file STRING
);
CREATE TABLE IF NOT EXISTS FINTECH_PROD.RAW.MERCHANTS_API_RAW (
    raw_payload VARIANT, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), _source_file STRING
);
 
COPY INTO FINTECH_PROD.RAW.CUSTOMERS_API_RAW (raw_payload, _source_file)
FROM (SELECT $1, METADATA$FILENAME FROM @FINTECH_PROD.RAW.CUSTOMERS_API_STAGE)
FILE_FORMAT = (FORMAT_NAME = FINTECH_PROD.RAW.NDJSON_FORMAT) ON_ERROR = 'CONTINUE';
 
COPY INTO FINTECH_PROD.RAW.ACCOUNTS_API_RAW (raw_payload, _source_file)
FROM (SELECT $1, METADATA$FILENAME FROM @FINTECH_PROD.RAW.ACCOUNTS_API_STAGE)
FILE_FORMAT = (FORMAT_NAME = FINTECH_PROD.RAW.NDJSON_FORMAT) ON_ERROR = 'CONTINUE';
 
COPY INTO FINTECH_PROD.RAW.MERCHANTS_API_RAW (raw_payload, _source_file)
FROM (SELECT $1, METADATA$FILENAME FROM @FINTECH_PROD.RAW.MERCHANTS_API_STAGE)
FILE_FORMAT = (FORMAT_NAME = FINTECH_PROD.RAW.NDJSON_FORMAT) ON_ERROR = 'CONTINUE';
 
SELECT * FROM FINTECH_PROD.RAW.CUSTOMERS_API_RAW;  -- rows = files loaded, not customers
-- unpack example:
SELECT f.value:customer_id::STRING, f.value:first_name::STRING
FROM FINTECH_PROD.RAW.CUSTOMERS_API_RAW, LATERAL FLATTEN(input => raw_payload:records) f
LIMIT 10;

