-- ============================================================================
-- Dynamic Tables configured for a daily (24-hour) refresh cycle.
-- Evaluates all partner transactions accumulated over the past 24 hours
-- and routes them into clean vs. quarantine in a single daily batch.
-- ============================================================================

CREATE OR REPLACE DYNAMIC TABLE FINTECH_PROD.RAW.PARTNER_TRANSACTIONS_CLEAN
    TARGET_LAG = '1 day'
    WAREHOUSE = INGEST_WH
AS
SELECT *
FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS
WHERE raw_payload:event_id IS NOT NULL
  AND raw_payload:account_id IS NOT NULL
  AND raw_payload:merchant_id IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE FINTECH_PROD.GOVERNANCE.PARTNER_TRANSACTIONS_QUARANTINE
    TARGET_LAG = '1 day'
    WAREHOUSE = INGEST_WH
AS
SELECT *
FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS
WHERE raw_payload:event_id IS NULL
   OR raw_payload:account_id IS NULL
   OR raw_payload:merchant_id IS NULL;

SELECT COUNT(*) FROM FINTECH_PROD.RAW.PARTNER_TRANSACTIONS_CLEAN;
SELECT COUNT(*) FROM FINTECH_PROD.GOVERNANCE.PARTNER_TRANSACTIONS_QUARANTINE;

GRANT SELECT ON TABLE FINTECH_PROD.GOVERNANCE.PARTNER_TRANSACTIONS_QUARANTINE TO ROLE FINTECH_TRANSFORMER;

GRANT USAGE ON PROCEDURE FINTECH_PROD.GOVERNANCE.LOAD_AND_VALIDATE_SETTLEMENTS() TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE ON PROCEDURE FINTECH_PROD.GOVERNANCE.LOAD_AND_VALIDATE_EXCHANGE_RATES() TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE ON PROCEDURE FINTECH_PROD.GOVERNANCE.LOAD_AND_VALIDATE_SUPPORT_CASES() TO ROLE FINTECH_TRANSFORMER;
GRANT USAGE ON PROCEDURE FINTECH_PROD.GOVERNANCE.LOAD_AND_VALIDATE_ACCOUNT_ACTIVITY() TO ROLE FINTECH_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE ON TABLE FINTECH_PROD.GOVERNANCE.SCHEMA_SNAPSHOTS TO ROLE FINTECH_TRANSFORMER;

SHOW GRANTS TO ROLE FINTECH_TRANSFORMER;